version: '3'
services:
  auditor:
    build: ./auditor
    command: bash
    stdin_open: true 
    tty: true
    ports:
      - "7002:8900"
  
  truffle:
    build: ./truffle
    # image: ccdle12/truffle
    command: bash
    stdin_open: true 
    tty: true
    ports: 
      - "7001:8080"
    volumes:
      - ./:/code

  ganache:
    build: ./ganache
    # image: ccdle12/ganache-cli
    ports:
      - "7000:8545"
  
